const gamingProducts = [
  {
    id: 0,
    type: "gaming",
    name: "Xbox One",
    rating: 4.1,
    price: "$449.99",
    imageSrc: "images/xboxone.png",
  },
  {
    id: 1,
    type: "gaming",
    name: "Playstation 4",
    rating: 4.3,
    price: "$449.99",
    imageSrc: "images/ps4.png",
  },
  {
    id: 2,
    type: "gaming",
    name: "Nintendo Switch",
    rating: 4.4,
    price: "$349.99",
    imageSrc: "images/switch.png",
  },
  {
    id: 3,
    type: "gaming",
    name: "Nintendo Switch Pad",
    rating: 4.4,
    price: "$99.99",
    imageSrc: "images/switchpad.png",
  },
  {
    id: 4,
    type: "gaming",
    name: "PS4 Controller Design",
    rating: 4,
    price: "$149.99",
    imageSrc: "images/ps4con.png",
  },
  {
    id: 5,
    type: "gaming",
    name: "PS4 Controller Black",
    rating: 4.4,
    price: "$149.99",
    imageSrc: "images/ps4conblack.png",
  },
  {
    id: 6,
    type: "gaming",
    name: "PS4 Controller White",
    rating: 4.5,
    price: "$149.99",
    imageSrc: "images/ps4conwhite.png",
  },
  {
    id: 7,
    type: "gaming",
    name: "Xbox Controller Design",
    rating: 4.3,
    price: "$139.99",
    imageSrc: "images/xcon.png",
  },
  {
    id: 8,
    type: "gaming",
    name: "Xbox Controller Black",
    rating: 4.5,
    price: "$139.99",
    imageSrc: "images/xconblack.png",
  },
  {
    id: 9,
    type: "gaming",
    name: "Xbox Controller White",
    rating: 4.9,
    price: "$139.99",
    imageSrc: "images/xconwhite.png",
  },
];

const otherProducts = [
  {
    id: 1,
    type: "other",
    name: "HP Spectre x360 15",
    rating: 4.5,
    price: "$650.99",
    imageSrc: "images/HP Spectre x360 15.png",
  },
  {
    id: 2,
    type: "other",
    name: "HP Spectre x360 15",
    rating: 4,
    price: "$550.99",
    imageSrc: "images/laptop 3.png",
  },
  {
    id: 3,
    type: "other",
    name: "Apple Ipad 15",
    rating: 4.6,
    price: "$750.99",
    imageSrc: "images/ipad.png",
  },
  {
    id: 4,
    type: "other",
    name: "Apple iPhone 12 Pro",
    rating: 4.7,
    price: "$1000.99",
    imageSrc: "images/Apple-iPhone-12-Pro.png",
  },
  {
    id: 5,
    type: "other",
    name: "g233 prodigy gaming headset",
    rating: 4.5,
    price: "$450.99",
    imageSrc: "images/g233 prodigy gaming headset.png",
  },
  {
    id: 6,
    type: "other",
    name: "ROG Strixm Wireless gaming",
    rating: 4.4,
    price: "$350.99",
    imageSrc: "images/ROG StrixmWireless gaming headset.png",
  },
  {
    id: 7,
    type: "other",
    name: "Nike Running Shoese",
    rating: 4.5,
    price: "$250.99",
    imageSrc: "images/Nike Running Shoese.png",
  },
  {
    id: 8,
    type: "other",
    name: "Running Shoes",
    rating: 4.4,
    price: "$150.99",
    imageSrc: "images/Running Shoes.png",
  },
];

export { gamingProducts, otherProducts };
